import os; os.chdir(r"C:\Users\80996\Documents\项目\像素铁道")
with open("pages/realtime.html","r",encoding="utf-8") as f: c=f.read()
c=c.replace("<div id=\"realtimeStatusContainer\" class=\"pixel-card\">\n      <div id=\"realtimeFilterBar\" class=\"rs-filter-bar\"></div>\n    </div>","<div id=\"realtimeFilterBar\" class=\"rs-filter-bar\"></div>\n    <div id=\"realtimeStatusContainer\" class=\"pixel-card\"></div>")
with open("pages/realtime.html","w",encoding="utf-8",newline="") as f: f.write(c)
print("rt ok")
with open("pages/trains.html","r",encoding="utf-8") as f: c=f.read()
c=c.replace("<div id=\"trainsLineListContent\" class=\"pixel-card\">\n  <div id=\"trainsFilterBar\" class=\"rs-filter-bar\"></div>\n\n</div>","<div id=\"trainsFilterBar\" class=\"rs-filter-bar\"></div>\n<div id=\"trainsLineListContent\" class=\"pixel-card\">\n\n</div>")
with open("pages/trains.html","w",encoding="utf-8",newline="") as f: f.write(c)
print("tr ok")
