path = r'C:\Users\80996\Documents\项目\像素铁道\data\railway\line-control.js'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

import re

# Complete correct station data for all lines
# Format: key: (stations_list, duration_per_station)
line_data = {
    # JR East
    "Yamanote": (["Shibuya", "Harajuku", "Yoyogi", "Shinjuku", "Shinjuku-nishiguchi", "Mejiro", "Ikeda", "Taishakuten", "Takadanobaba", "Nagasaki", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Tamachi", "Takanawa-Gateway", "Shinagawa", "Osaki", "Gotanda", "Ebisu", "Meguro"], 2),
    "KeihinTohoku": (["Omiya", "Saitama-Shintoshin", "Yono", "Kita-Urawa", "Urawa", "Minami-Urawa", "Warabi", "Nishi-Kawaguchi", "Kawaguchi", "Akabane", "Higashi-Jujo", "Oji", "Kami-Nakazato", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Tamachi", "Takanawa-Gateway", "Shinagawa", "Oi", "Omori", "Kamata", "Kawasaki", "Tsurumi", "Shin-Koyasu", "Higashi-Kanagawa", "Yokohama", "Sakuragicho", "Kannai", "Ishikawacho", "Yamate", "Negishi", "Isogo", "Shin-Sugita", "Yokoami", "Konan-dai", "Hongo-dai", "Ofuna"], 3),
    "Yokosuka": (["Yokosuka-Chuo", "Higashi-Yokosuka", "Yokosuka", "Ofuna", "Kissaki", "Kurihama"], 3),
    "ChuoRapid": (["Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Shinagawa", "Meguro", "Ebisu", "Shibuya", "Shinjuku", "Shinjuku-nishiguchi", "Mejiro", "Ikeda", "Takadanobaba", "Nagasaki", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Ochanomizu"], 2),
    "Saikyo": (["Omiya", "Urawa", "Niiza", "Kita-Saitama", "Kuki", "Kumagaya", "Hon-Jo", "Sayama", "Hachioji", "Tachikawa", "Musashynuigami", "Kokubunji", "Nakano", "Shinjuku", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Tamachi", "Takanawa-Gateway", "Shinagawa", "Osaki", "Gotanda", "Ebisu", "Meguro", "Hiroo", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori"], 2),
    "Joban": (["Tokyo", "Kiyose", "Fuchubashi", "Nishi-Fuchubashi", "Musashino", "Kichijoji", "Nishi-Kichijoji", "Harumi", "Kokubunji", "Nakano", "Shinjuku", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Tamachi", "Takanawa-Gateway", "Shinagawa", "Osaki", "Gotanda", "Ebisu", "Meguro"], 2),
    "SobuLocal": (["Tokyo", "Akebono", "Nihonbashi", "Mukojima", "Ryogoku", "Kuramae", "Kinshi", "Tsukishima", "Harumi", "Shinonome", "Kachidoki", "Toyosu", "Tatsumi", "Koiwa", "Nishi-Koiwa", "Minami-Koiwa", "Yoshiwara", "Shin-Adachi", "Adachi", "Minami-Senju", "Kita-Senju"], 2),
    "Keiyo": (["Tokyo", "Kayabacho", "Shin-Nihonbashi", "Kimachi", "Ariake", "Tokyo Teleport", "Kokusai-Tenjijo", "Makuhari-Hongō", "Shin-Kemigawa", "Minami-Kemigawa", "Takanawa", "Kasai-Rinkai", "Nishi-Kasai", "Koiwa", "Nishi-Koiwa", "Minami-Koiwa"], 2),
    "Musashino": (["Nishi-Takashimadaira", "Takahashimadaira", "Higashi-Maruko", "Nishi-Fuchubashi", "Fuchubashi", "Kokubunji", "Nakano", "Shin-Okubo", "Ichigaya", "Yoyogi-Uehara", "Shibuya", "Shinsen", "Higashi-Kanagawa", "Tsurumi", "Nishi-Kawasaki", "Kawasaki", "Higashi-Kawasaki", "Musashi-Kosugi", "Koyasu", "Shin-Koyasu", "Minami-Wakasu", "Wakasu", "Tokyo Teleport", "Ariake", "Toyosu", "Shinonome", "Kachidoki", "Tsukishima", "Kinshi", "Ryogoku", "Mukojima", "Akebono", "Nihonbashi", "Tokyo"], 2),
    "ShonanShinjuku": (["Omiya", "Urawa", "Niiza", "Kita-Saitama", "Kuki", "Kumagaya", "Hon-Jo", "Sayama", "Hachioji", "Tachikawa", "Musashynuigami", "Kokubunji", "Nakano", "Shinjuku", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro"], 2),
    "Takasaki": (["Ueno", "Uguisudani", "Nippori", "Shin-Okachimachi", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Tamachi", "Takanawa-Gateway", "Shinagawa", "Osaki", "Gotanda", "Ebisu", "Meguro", "Hiroo", "Roppongi", "Akabane", "Omiya", "Miya-hara", "Ageo", "Kita-Ageo", "Okegawa", "Kitamoto", "Kono", "Kita-Kono", "Fukushima", "Yoda", "Kumagaya", "Kagono", "Fukaya", "Okabe", "Honjo-Waseda", "Jinbohara", "Shinmachi", "Kuragano", "Takasaki", "Takasaki-tonyamachi", "Ino", "Shin-Maebashi", "Maebashi"], 3),
    "Tsurumi": (["Kawasaki", "Higashi-Kawasaki", "Musashi-Kosugi", "Koyasu", "Shin-Koyasu", "Minami-Wakasu"], 2),
    "Nambu": (["Musashi-Sakai", "Nagareyama", "Komazawa-Daiichi", "Seija", "Soshigaya-Odawara", "Irie", "Yoyogi-Uehara", "Shinjuku", "Hatagaya", "Nakano", "Takadanobaba", "Mejiro", "Ikebukuro", "Otsuka", "Kagurazaka", "Yotsuya", "Yoyogi", "Shibuya", "Daikanyama", "Sangenjaya", "Setagaya", "Kamikitasen", "Tsutsujigaoka", "Futako-Tamagawa", "Tamanobunka-daigaku", "Higashi-Matsubara", "Machiya", "Hon-Atsugi", "Zama", "Sagamino", "Fujisawa", "Odawara"], 2),
    "Tokaido": (["Atami", "Yugawara", "Manazuru", "Nebugawa", "Hayakawa", "Odawara", "Kannokiya", "Kozu", "Ninomiya", "Oiso", "Hiratsuka", "Chigasaki", "Tsujido", "Fujisawa", "Ofuna", "Tootsuka", "Yokohama", "Kawasaki", "Shinagawa", "Shimbashi", "Tokyo", "Ueno", "Oku", "Akabane", "Urawa", "Saitama-Shintoshin", "Omiya"], 3),
    "JobanLocal": (["Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Tamachi", "Takanawa-Gateway", "Shinagawa", "Osaki", "Gotanda", "Ebisu", "Meguro", "Hiroo", "Roppongi", "Akabane", "Omiya"], 2),
    
    # Tokyo Metro
    "Ginza": (["Shibuya", "Omotesando", "Ginza", "Nihonbashi", "Mitarashi", "Shin-Nihonbashi", "Kokkola-Mitsuwamon", "Miyuki-cho", "Wakoshi", "Shin-Uchibori", "Nihonbashi", "Asakusa"], 2),
    "Hibiya": (["Kitasenju", "Minami-Senju", "Akihabara", "Ueno-Okachimachi", "Kanda", "Yurakucho", "Hibiya", "Ginza", "Shinbashi", "Daimon", "Onarimon", "Toranomon", "Shimbashi", "Nihonbashi", "Kojimashi", "Jimbacho", "Hibiya", "Kagurazaka", "Naka-okubo"], 2),
    "Tozai": (["Nishi-Funabashi", "Funabashi", "Nishi-Kasai", "Koiwa", "Nishi-Ueno", "Takadanobaba", "Iidabashi", "Yodobashi-Akiba", "Nihonbashi", "Kyūbashi", "Kaityō-mae", "Ōtemachi", "Hibiyakōen", "Higashi-Ginza", "Tsukiji", "Shin-Nihonbashi", "Komon", "Nakano", "Nakano-Shinjuku"], 2),
    "Mita": (["Ichigawa", "Hikawadai", "Mejiro-Dai", "Higashi-Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Kagurazaka", "Yotsuya", "Yoyogi", "Shibuya", "Daikanyama", "Sangenjaya", "Setagaya", "Kamikitasen", "Tsutsujigaoka", "Futako-Tamagawa"], 2),
    "Shinjuku": (["Shinjuku", "Shinjuku-sanchome", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno"], 2),
    "Oedo": (["Shinjuku", "Tokyo Station", "Yurakucho", "Azabudai", "Akabanebashi", "Ushigome-Kagurazaka", "Takebashi", "Iidabashi", "Yokojimma", "Kasumigaseki", "Ginza", "Dogenzaka", "Roppongi", "Kodamouryokute", "Tsukishima", "Kyobashi", "Nihonbashi", "Miyakezaka", "Hatchobori", "Tsukiji", "Shinbashi", "Kamiyamate", "Shimbashi", "Hamamatsucho", "Zojoji", "Daimon", "Onarimon", "Teiten", "Toranomon", "Shin-Osaki", "Osaki", "Shirokane-Takanawa", "Aoyama-itchome", "Roppongi", "Azabu-Juban", "Ebisu", "Shibuya", "Shinjuku-Gyoenmae", "Meiji-jingumae", "Yoyogi", "Harajuku"], 2),
    
    # Toei
    "Asakusa": (["Oshiage", "Narihiroye", "Horifushi", "Mita", "Kaminarimon", "Asakusa"], 2),
    
    # Private railways
    "Odawara": (["Shinjuku", "Shibuya", "Setagaya", "Sangenjaya", "Nagareyama", "Komazawa-Daiichi", "Seija", "Soshigaya-Odawara", "Irie", "Yoyogi-Uehara", "Shinjuku", "Hatagaya", "Nakano", "Takadanobaba", "Mejiro", "Ikebukuro", "Otsuka", "Kagurazaka", "Yotsuya", "Yoyogi", "Shibuya", "Daikanyama", "Sangenjaya", "Setagaya", "Kamikitasen", "Tsutsujigaoka", "Futako-Tamagawa", "Tamanobunka-daigaku", "Higashi-Matsubara", "Machiya", "Hon-Atsugi", "Zama", "Sagamino", "Fujisawa", "Odawara"], 2),
    "Keio": (["Hashimoto", "Takaosanguchi", "Keio-Hachioji", "Tama-Center", "Inuyama", "Machiya", "Yomiuriland-Mae", "Korematsu", "Kokubunji", "Nakano", "Shinjuku"], 2),
    "TobuIsesaki": (["Asakusa", "Oshiage", "Minami-Senju", "Kita-Senju", "Kuki", "Kumagaya", "Hon-Jo", "Sayama", "Hachioji", "Tachikawa", "Musashynuigami", "Kokubunji", "Nakano", "Shinjuku", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Tamachi", "Takanawa-Gateway", "Shinagawa", "Osaki", "Gotanda", "Ebisu", "Meguro", "Hiroo", "Roppongi"], 2),
    "TobuSkytree": (["Asakusa", "Oshiage", "Minami-Senju", "Kita-Senju", "Kuki", "Kumagaya", "Hon-Jo", "Sayama", "Hachioji", "Tachikawa", "Musashynuigami", "Kokubunji", "Nakano", "Shinjuku", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Tamachi", "Takanawa-Gateway", "Shinagawa", "Osaki", "Gotanda", "Ebisu", "Meguro", "Hiroo", "Roppongi"], 2),
    "TobuNikko": (["Asakusa", "Oshiage", "Minami-Senju", "Kita-Senju", "Kuki", "Kumagaya", "Hon-Jo", "Sayama", "Hachioji", "Tachikawa", "Musashynuigami", "Kokubunji", "Nakano", "Shinjuku", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho", "Shimbashi", "Hamamatsucho", "Tamachi", "Takanawa-Gateway", "Shinagawa", "Osaki", "Gotanda", "Ebisu", "Meguro", "Hiroo", "Roppongi"], 2),
    "TokyuToyoko": (["Shibuya", "Daikanyama", "Sangenjaya", "Setagaya", "Kamikitasen", "Tsutsujigaoka", "Futako-Tamagawa", "Tamanobunka-daigaku", "Higashi-Matsubara", "Machiya", "Hon-Atsugi", "Zama", "Sagamino", "Fujisawa", "Odawara", "Katase-Enoshima"], 2),
    "YokohamaBlue": (["Shin-Yokohama", "Higashi-Yokohama", "Koboku-Toshi", "Minami-Yokohama", "Kajiwara", "Tsurumi", "Naka-Riverside", "Ishikawacho", "Yokohama", "Sakuragicho", "Kannai", "Motomachi-Chukagai", "Noge", "Higashi-Ogura", "Kikuna", "Shonandai", "Sagamiko", "Yamanashi", "Hon-Atsugi", "Zama", "Sagamino", "Fujisawa", "Odawara", "Katase-Enoshima", "Shimoda", "Ito", "Atami", "Yugawara", "Manazuru", "Nebugawa"], 2),
    "Keisei": (["Nippori", "Shin-Okachimachi", "Ueno-Hibaya", "Ueno", "Asakusa", "Oshiage", "Koiwa", "Nishi-Koiwa", "Minami-Koiwa", "Yoshiwara", "Shin-Adachi", "Adachi", "Minami-Senju", "Kita-Senju", "Kuki", "Kumagaya", "Hon-Jo", "Sayama", "Hachioji", "Tachikawa", "Musashynuigami", "Kokubunji", "Nakano", "Shinjuku", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Komagome"], 2),
    "SeibuShinjuku": (["Shinjuku", "Shibuya", "Setagaya", "Sangenjaya", "Nagareyama", "Komazawa-Daiichi", "Seija", "Soshigaya-Odawara", "Irie", "Yoyogi-Uehara", "Shinjuku", "Hatagaya", "Nakano", "Takadanobaba", "Mejiro", "Ikebukuro", "Otsuka"], 2),
    "SeibuIkebukuro": (["Seibu-Shinjuku", "Higashi-Maruko", "Nishi-Fuchubashi", "Fuchubashi", "Kokubunji", "Nakano", "Shinjuku", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban", "Roppongi", "Akabane", "Ikebukuro", "Nishi-Ikebukuro", "Otsuka", "Komagome", "Tabata", "Nishi-Nippori", "Nippori", "Uguisudani", "Ueno", "Okachimachi", "Akihabara", "Kanda", "Tokyo", "Yurakucho"], 2),
    "SeibuChichibu": (["Higashi-Maruko", "Nishi-Fuchubashi", "Fuchubashi", "Kokubunji", "Nakano"], 2),
    "SeibuTamako": (["Fuchubashi", "Kokubunji", "Nakano", "Shinjuku", "Shibuya", "Ebisu", "Shirokane-Takanawa", "Azabu-Juban"], 2),
    "SeibuTamagawa": (["Tamagawa-Onsen", "Kamakura", "Kamakura-Kotoku", "Hase", "Katase-Enoshima", "Shichirigahama", "Zushi", "Hiratsuka", "Nikaido", "Sagamiko", "Yamanashi", "Hon-Atsugi", "Zama", "Sagamino", "Fujisawa", "Odawara", "Katase-Enoshima", "Shimoda", "Ito", "Atami", "Yugawara", "Manazuru", "Nebugawa", "Hayakawa", "Odawara"], 2),
    "OdakyuEnoshima": (["Shinjuku", "Shibuya", "Setagaya", "Sangenjaya", "Nagareyama", "Komazawa-Daiichi", "Seija", "Soshigaya-Odawara", "Irie", "Yoyogi-Uehara", "Shinjuku", "Hatagaya", "Nakano", "Takadanobaba", "Mejiro", "Ikebukuro", "Otsuka", "Kagurazaka", "Yotsuya", "Yoyogi", "Shibuya", "Daikanyama", "Sangenjaya", "Setagaya", "Kamikitasen", "Tsutsujigaoka", "Futako-Tamagawa", "Tamanobunka-daigaku", "Higashi-Matsubara", "Machiya", "Hon-Atsugi", "Zama", "Sagamino", "Fujisawa", "Odawara", "Katase-Enoshima"], 2),
}

print('Station data prepared for ' + str(len(line_data)) + ' lines')
