const fs = require('fs');
const d = JSON.parse(fs.readFileSync('data/core/railway_data.json', 'utf8'));
const keys = Object.keys(d);
console.log('Top keys:', keys.slice(0, 6).join(', '));
const li = d.lineIds || {};
const st = d.stations || {};
const nm = d.name_map || {};
const tm = d.tourism || {};
console.log('Lines:', Object.keys(li).length);
console.log('Stations:', Object.keys(st).length);
console.log('NameMap:', Object.keys(nm).length);
console.log('Tourism:', Object.keys(tm).length);
