const fs=require("fs"),path=require("path"),assert=require("assert"),vm=require("vm");
const window={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,"..","data/timetables/train-operation-evidence.js"),"utf8"),{window,console});
const n=window.TrainOperationEvidence.normalizeOperationCode;
assert.strictEqual(n("03K",{lineId:"Tozai"}),"03K");
assert.strictEqual(n("507K",{lineId:"Tozai"}),"07K");
assert.strictEqual(n("603K",{lineId:"Tozai"}),"03K");
assert.strictEqual(n("655S",{lineId:"Tozai"}),"55S");
assert.strictEqual(n("689S",{lineId:"Tozai"}),"89S");
assert.strictEqual(n("A650T",{lineId:"Tozai"}),"50T");
assert.strictEqual(n("A750TR",{lineId:"Tozai"}),"50T");
assert.strictEqual(n("A1291G",{lineId:"TokyuToyoko"}),"91G");
assert.strictEqual(n("B691G",{lineId:"TokyuToyoko"}),"91G");
assert.strictEqual(n("026-081",{lineId:"Denentoshi"}),"","numeric public train number must not infer K operation ownership");
assert.strictEqual(n("057-102",{lineId:"Hanzomon"}),"","numeric public train number must not infer S operation ownership");
assert.strictEqual(n("050-001",{lineId:"Denentoshi"}),"","numeric public train number must not infer T operation ownership");
assert.strictEqual(n("2601",{lineId:"SeibuShinjuku"}),"","plain train numbers must not be guessed as operation codes");
assert.strictEqual(n("1234",{lineId:"Tozai"}),"","unknown numeric Tozai train number must remain unresolved");
console.log("Operation code normalization: PASS");