const assert = require("assert");
const E = require("../js/runinfo-evaluator.js");
function st(text){ return E.evaluate({text}).status; }
assert.strictEqual(st("現在、平常通り運転しています。"), "normal");
assert.strictEqual(st("現在、平常どおり運転しています。"), "normal");
assert.strictEqual(st("平常運転"), "normal");
assert.strictEqual(st("平常運行"), "normal");
assert.strictEqual(st("通常運転"), "normal");
let toei=E.evaluate({text:"現在、１５分以上の遅延はありません。"});
assert.strictEqual(toei.status,"normal"); assert.strictEqual(toei.maxDelay,null); assert.strictEqual(toei.delayUpperBoundMinutes,15);
assert.strictEqual(st("一部列車が運休しています。"),"notice");
assert.strictEqual(st("全線で運転を見合わせています。"),"suspended");
assert.strictEqual(st("B線の運転見合わせの影響により、B線との直通運転を中止しています。"),"notice");
assert.strictEqual(st("B線との直通運転を中止しています。ダイヤが乱れています。"),"delayed");
assert.strictEqual(st("A駅～B駅間で運転を見合わせています。"),"suspended");
assert.strictEqual(st("運休のお知らせがあります。"),"info");
assert.strictEqual(E.evaluate({structuredStatus:"Suspension",text:"直通運転を中止しています。"}).status,"suspended");
assert.strictEqual(E.evaluate({signalStatus:"delayed",text:""}).status,"delayed");
let meta=E.evaluate({structuredStatus:"Delay",text:"信号確認のため約12分遅れています。18時08分頃再開予定。",range:"A駅間～B駅間",cause:"信号確認",resumeEstimate:"2026-10-02T18:08:00+09:00"});
assert.strictEqual(meta.status,"delayed");
assert.strictEqual(meta.maxDelay,12);
assert.strictEqual(meta.interval,"A駅→B駅");
assert.strictEqual(meta.cause,"信号確認");
assert.strictEqual(meta.resume,"18:08");
assert.ok(meta.detail.indexOf("信号確認")>=0);
let clockOnly=E.evaluate({structuredStatus:"Normal",text:"18時08分頃に再開しました。"});
assert.strictEqual(clockOnly.maxDelay,null);
let stations=E.extractMetadata({stationFromName:"新宿",stationToName:"中野",text:""});
assert.strictEqual(stations.interval,"新宿→中野");
let textRange=E.extractMetadata({text:"A駅～B駅間で運転を見合わせています。"});
assert.strictEqual(textRange.interval,"A駅→B駅");
let liveRange=E.extractMetadata({text:"長野原草津口〜大前駅間の上下線で運転を見合わせています。"});
assert.strictEqual(liveRange.interval,"長野原草津口→大前駅");
let fromToRange=E.extractMetadata({text:"A駅からB駅までの上下線で運転を見合わせています。"});
assert.strictEqual(fromToRange.interval,"A駅→B駅");
let fromToDown=E.extractMetadata({text:"新宿駅から中野駅までの下り線で遅れが出ています。"});
assert.strictEqual(fromToDown.interval,"新宿駅→中野駅");
let wholeRange=E.extractMetadata({text:"全線で運転を見合わせています。"});
assert.strictEqual(wholeRange.interval,"全線");
let structuredWins=E.extractMetadata({text:"A駅～B駅間で遅れています。",range:"C駅～D駅"});
assert.strictEqual(structuredWins.interval,"C駅→D駅");
console.log("runinfo-evaluator: 28 PASS");
