-- Restored baseline for production migration 20261003032912.
-- Reconstructed from the live public schema. Later railway evidence migrations are
-- intentionally represented by their own recorded migration files.

create table if not exists public.stations (
  id text primary key, name text not null, latitude numeric not null, longitude numeric not null,
  created_at timestamptz not null default now()
);
create table if not exists public.railway_lines (
  id varchar primary key, name_jp varchar, name_en varchar, code varchar, color varchar,
  operator varchar, type varchar, duration_total_min integer, branch_of varchar
);
create table if not exists public.line_stations (
  id integer primary key, line_id varchar references public.railway_lines(id),
  station_name varchar, station_index integer
);
create index if not exists idx_line_stations_line_id on public.line_stations(line_id);
create table if not exists public.tags (id text primary key);
create table if not exists public.tag_translations (
  id bigint generated by default as identity primary key, tag_id text not null references public.tags(id),
  language text not null, name text not null, unique (tag_id, language)
);
create table if not exists public.spots (
  id text primary key, station_id text not null references public.stations(id), emoji text,
  distance text, direction text, cover_image text, sort integer not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists idx_spots_station on public.spots(station_id);
create table if not exists public.spot_translations (
  id bigint generated by default as identity primary key, spot_id text not null references public.spots(id),
  language text not null, title text not null, content text not null, unique (spot_id, language)
);
create index if not exists idx_spot_translations_lookup on public.spot_translations(spot_id, language);
create table if not exists public.spot_images (
  id bigint generated by default as identity primary key, spot_id text not null references public.spots(id),
  image_url text not null, thumbnail text, sort integer not null default 0
);
create table if not exists public.spot_tags (
  spot_id text not null references public.spots(id), tag_id text not null references public.tags(id),
  primary key (spot_id, tag_id)
);

alter table public.stations enable row level security;
alter table public.railway_lines enable row level security;
alter table public.line_stations enable row level security;
alter table public.tags enable row level security;
alter table public.tag_translations enable row level security;
alter table public.spots enable row level security;
alter table public.spot_translations enable row level security;
alter table public.spot_images enable row level security;
alter table public.spot_tags enable row level security;
