create table if not exists public.train_run_stops (
  id bigint generated by default as identity primary key,
  train_run_id bigint not null references public.train_runs(id) on delete cascade,
  stop_sequence integer not null,
  station_key text not null,
  station_urn text,
  arrival_time time without time zone,
  departure_time time without time zone,
  arrival_minute integer,
  departure_minute integer,
  created_at timestamptz not null default now(),
  unique (train_run_id, stop_sequence)
);

alter table public.train_run_stops enable row level security;

create index if not exists train_run_stops_run_sequence_idx
  on public.train_run_stops(train_run_id, stop_sequence);

create index if not exists train_runs_lookup_idx
  on public.train_runs(service_date, network_key, train_number);

revoke all on public.train_run_stops from anon, authenticated;
